### ISSUE TITLE
code error occurs when we save order bump while order bump schedule empty

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#38]
os: window10
wp version:5.8
wc version: 5.6.0
version:1.4.3-opt
path: save order bump
description: getting code error while we saving order and when order bump schedule is empty
![schedule -2021 09 04-12_48_11](https://user-images.githubusercontent.com/86113814/132086447-bcfd573d-8f7a-4455-b687-48c5f9886e10.png)

**Comment by ced-ashutoshv** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
not fix, still getting same issue
https://www.awesomescreenshot.com/video/5144474?key=65e9bd5e78f0f0967b7b39282b50aa8c

**Comment by ced-ashutoshv** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
fix
